stages:
  - test
  - build

build:
  services:
    - name: docker:24.0.7-dind
      alias: docker
  stage: build
  image: docker:24.0.7
  script:
    - docker login -u $DOCKER_USERNAME --password $DOCKER_TOKEN
    - docker build -t $DOCKER_USERNAME/backend-al2:latest .
    - docker push $DOCKER_USERNAME/backend-al2:latest